version: '3.7'

services:
    
    db:
        image: mcr.microsoft.com/mssql/server
        environment:
            - SA_PASSWORD=MyAw@someP@ssw0rd
            - ACCEPT_EULA=Y
        ports:
            - "1433:1433"

        volumes:
          - data:/var/opt/mssql

volumes:
  data:
